### ISSUE TITLE
Cannot find module 'openzeppelin-solidity/contracts/utils/Context.sol'

### ISSUE THREAD

**Issue by 978740431** [rkalis/truffle-plugin-verify#117] opened 2021-09-29 10:11 UTC
```
➜ simpletoken truffle run verify WrappedSelfETH --network ropsten --debug
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.15
Verifying WrappedSelfETH
Reading artifact file at /Users/zhangnan/blockchain/simpletoken/build/contracts/WrappedSelfETH.json
Retrieving constructor parameters from https://api-ropsten.etherscan.io/api?apiKey=3QH9TTYIWSC5MJYC1CJEQUNSJ2RFT7KPDU&module=account&action=txlist&address=0xBf655E2b118bdc4581e345186DF030352f74688d&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x
Cannot find module 'openzeppelin-solidity/contracts/utils/Context.sol'
Failed to verify 1 contract(s): WrappedSelfETH
```

### my contact
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "openzeppelin-solidity/contracts/access/Ownable.sol";

contract WrappedSelfETH is ERC20, ERC20Burnable, Ownable {
    constructor() ERC20("wrapped ETH", "WETH") {
        _mint(msg.sender, 20000 * 10 ** decimals());
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }
}
```

### truffle-config.js
```
 const HDWalletProvider = require('truffle-hdwallet-provider');
 const fs = require('fs');
 const mnemonic = fs.readFileSync(".secret").toString().trim();

module.exports = {
  
  networks: {

    ropsten: {
      provider: () => new HDWalletProvider(mnemonic, `https://ropsten.infura.io/v3/0fef7f32ccd549f998137fe6b6b7422e`),
      network_id: 3,       // Ropsten's id
      gas: 6000000,        // Ropsten has a lower block limit than mainnet
      confirmations: 2,    // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
  },

  mocha: {
    // timeout: 100000
  },

  compilers: {
    solc: {
      version: "0.8.0",    // Fetch exact version from solc-bin (default: truffle's version)
    }
  },

  api_keys: {
    etherscan: 'xxxxxxx',
    ropsten:'xxxxxx'
  },

  plugins: [
    'truffle-plugin-verify'
  ]
};

```

**Comment by fahadbraveknight** [comment] 2021-11-10 15:39
Facing this same issue, is this resolved?

**Comment by DAC-PhilThomsen** [comment] 2021-11-16 01:53
Just want to say I am facing the same issue with every single file I want to import at the moment. It is kind of weird, will update if I find some workaround.

**Comment by eulerbeat** [comment] 2021-11-23 03:29
Facing the same issue, one workaround is to flatten the file and verify.

**Comment by eulerbeat** [comment] 2021-11-23 03:34
Relevant SO - https://stackoverflow.com/a/67037823/13470566

**Comment by rkalis** [comment] 2021-11-24 19:24
So this issue looks similar to some other issues that were raised before such as #111. And the weird thing is that this does not happen with *all* imported contracts, otherwise there would be many more bug reports. So there must be *some* reason for why this happens *sometimes* but not for everyone. This issue is definitely on my list, but this makes it difficulyt to debug.

**Comment by rkalis** [comment] 2021-11-24 19:25
If there's anyone with a repository where you're experiencing this that I can take a look at, please let me know.

**Comment by juliensie** [comment] 2021-12-02 19:59
Hi @rkalis 

Same thing : https://github.com/trendev/greeting

**Comment by juliensie** [comment] 2021-12-02 20:00
```
> truffle run verify Greeter --network fuji
Verifying Greeter
Cannot find module '@openzeppelin/contracts/utils/Context.sol'
Require stack:
- /usr/local/lib/node_modules/truffle-plugin-verify/verify.js
- /usr/local/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/local/lib/node_modules/truffle/build/cli.bundled.js
Failed to verify 1 contract(s): Greeter

**Comment by juliensie** [comment] 2021-12-02 22:06
Well, it is a very basic smart contract using openzeppelin's `Ownable` so if you import the `.sol` contracts directly, it works : https://testnet.snowtrace.io/address/0xc0ea70bf310b43c7e3e5a60c209203f5788b66d5#readContract 

👉  https://github.com/trendev/greeting  ➡️  the `main` branch uses "`@openzeppelin`" imports and  the `issue-truffle-verify` branch uses local downloaded contract.

**Comment by juliensie** [comment] 2021-12-02 22:07
sounds like an issue during the imports parsing... 🤔

**Comment by juliensie** [comment] 2021-12-03 12:42
... I messed up w/ dependencies but it works 🆗

**Comment by rkalis** [comment] 2021-12-06 08:19
That's great, thanks for the repository! Will check it out.

**Comment by rkalis** [comment] 2021-12-06 08:57
I couldn't reproduce the issue on your repository @juliensie, verification worked fine for me. What OS + Node version are you using?

**Comment by juliensie** [comment] 2021-12-06 10:50
https://github.com/rkalis/truffle-plugin-verify/issues/117#issuecomment-985488649, solved buddy ✅

**Comment by rkalis** [comment] 2021-12-06 11:35
Oh I see, that's good to hear! Could you share what you were doing wrong and how you solved it? That could help other people who find this issue in the future.

**Comment by juliensie** [comment] 2021-12-06 11:38
I've just imported your package in the correct dependencies...

**Comment by rkalis** [comment] 2021-12-15 16:12
This issue has been open for a while, but it looks like it's a duplicate of #111 so I'm closing this issue. If you find this issue in the future, please join the conversation in that issue instead.

**Closed by rkalis** 2021-12-15 16:12 UTC
Labels: needs-investigation
