### ISSUE TITLE
Verifying Libraries Exposes Local Path

### ISSUE THREAD

**Issue by ss5nathan** [rkalis/truffle-plugin-verify#105] opened 2021-08-10 14:09 UTC
The settings portion of the verification exposes full local path to etherscan/bscscan. Below is an example. I would prefer for this not to happen, is there a way around this when using libraries? The specific issue I have is with this string "/Users/MYUSERNAME/MYLOCALPATHNAME/contract.sol" being exposed publicly.

`
{
  "optimizer": {
    "enabled": true,
    "runs": 200
  },
  "evmVersion": "istanbul",
 ** "libraries": {
    "/Users/MYUSERNAME/MYLOCALPATHNAME/contract.sol": {
      "libraryName": "0xLibraryAddress"
    }**
  },
}
`

**Comment by rkalis** [comment] 2021-08-24 14:02
This is a good point, and it should be possible to fix this. I'll need to find the time to figure that out though.

**Comment by rkalis** [comment] 2021-09-10 17:48
Hey @ss5nathan, I just tested with the latest versions of Truffle + truffle-plugin-verify, which should have fixed this issue due to the new `project:` prefix that was added by Truffle. Could you update to the latest truffle + truffle-plugin-verify to see if this issue is resolved on your side as well?

**Comment by niccolopetti** [comment] 2021-09-28 12:12
I have the same issue and I am using
```
"truffle": "^5.4.12"
"truffle-plugin-verify": "^0.5.15"
```
running on Ubuntu 20.10

**Comment by rkalis** [comment] 2021-09-28 15:44
Does the issue also persist if you remove the contracts `build/` folder and recompile + redeploy + reverify the contracts?

**Comment by rkalis** [comment] 2021-12-15 16:04
Can't debug this without a reproduction repo, so I'm closing this. Feel free to re-open with more info in the future.

**Closed by rkalis** 2021-12-15 16:04 UTC
Labels: bug, waiting
