### ISSUE TITLE
Mumbai Polygon API key Failed to Verify

### ISSUE THREAD

**Issue by shep-analytics** [rkalis/truffle-plugin-verify#129] opened 2021-11-18 05:21 UTC
With a valid API key from polygon, I always get that the API key is invalid trying to verify on the mumbai testnet. This plugin has saved me countless hours on other chains, I would love to be able to completely use it on MATIC.

Any help would be greatly appreciated!

```
truffle run verify Widget --network mumbai
Verifying Widget
Invalid API Key
Failed to verify 1 contract(s): Widget
```

**Comment by rkalis** [comment] 2021-11-18 10:53
Did you configure a separate API key for PolygonScan? You need to request a separate API key from PolygonScan to verify on Polygon / Mumbai, you can't use the same API key as with Etherscan.

**Comment by shep-analytics** [comment] 2021-11-22 03:21
Yes, I used a polygonScan API

Alex

**Comment by rkalis** [comment] 2021-12-06 18:33
Does this issue still persist?

**Comment by rkalis** [comment] 2021-12-20 15:26
This may be a duplicate of #97. If this issue persists, please provide any more information in that issue.

**Closed by rkalis** 2021-12-20 15:26 UTC
Labels: waiting
