### ISSUE TITLE
Failed to verify contracts with proxy

### ISSUE THREAD

**Issue by sidhujag** [rkalis/truffle-plugin-verify#18] opened 2019-09-12 20:41 UTC
Hey there again!

So we've added proxies to our contracts and I was trying to run verify again and found that it was erroring out, I see a "Fail - Unable to verify". Do you handle proxy implementations?

This is the repo: https://github.com/syscoin/sysethereum-contracts/tree/validateallheaders

**Comment by rkalis** [comment] 2019-09-13 12:47
Hey, I'm not sure what is needed to verify these kind of proxy contracts. Have you been able to verify them manually in Etherscan? What were the steps you took to make it work?

**Comment by sidhujag** [comment] 2019-09-13 14:43
i'll give it a try

**Comment by sidhujag** [comment] 2019-09-30 14:17
So I tried using openzeppelin to verify and it didn't work, on telegram the admin said he was able to do SyscoinSuperblocks manually:

https://rinkeby.etherscan.io/address/0x0c66b9b6b839a7647c49affc9fa7e4464f1d4a0d#code

but that openzeppelin may not support libraries, I know we do so I'm wondering where the desrepency is:
https://forum.openzeppelin.com/t/openzeppelin-verify-failing-for-contract-with-library/1438

**Comment by rkalis** [comment] 2019-10-03 00:16
I haven't been able to verify it succesfully, but if the issue is with the library link, perhaps you could try to manually hack the library links into the artifact. Or alternatively, if you can show me what steps you took to go from 

```
truffle compile
truffle migrate --network rinkeby
```

to verifying the contract. I.e. where did you get the required information to pass into the web form on the Etherscan website?

**Comment by rkalis** [comment] 2020-10-01 22:28
It's been a year without any activity, so I'm closing this issue. Feel free to re-open with more information.

**Closed** 2020-10-01 22:29 UTC
