### ISSUE TITLE
issues with solc 0.5.10 and truffle v5.0.24

### ISSUE THREAD

**Issue by sidhujag** [rkalis/truffle-plugin-verify#11] opened 2019-07-09 04:35 UTC
Truffle v5.0.24 (core: 5.0.24)
Solidity v0.5.0 (solc-js)
Node v11.13.0
Web3.js v1.0.0-beta.37

Verifying SyscoinBattleManager
{"status":"0","message":"NOTOK","result":"Fail - Unable to verify"}
Fail - Unable to verify

Failed to verify 1 contract(s): SyscoinBattleManager

The input is like this:
{ apikey: '<blanked>',
  module: 'contract',
  action: 'verifysourcecode',
  contractaddress: '0x47C450C0c189E4E6DdbE84AdCB4FF7E3e06d0601',
  sourceCode:
   'pragma solidity ^0.5.10;\n\n/**\n * @dev Wrappers over Solidity\'s arithmetic operations with added overflow\n * checks.\n *\n * Arithmetic operations in Solidity wrap on overflow. This can easily result\n * in bugs, because programmers usually assume that an overflow raises an\n * error, which is the standard behavior in high level programming languages.\n * `SafeMath` restores this intuition by reverting the transaction when an\n * operation overflows.\n *\n * Using this library instead of the unchecked operations eliminates an entire\n * class of bugs, so it\'s recommended to use it always.\n */\nlibrary SafeMath {\n    /**\n     * @dev Returns the addition of two unsigned integers, reverting on\n     * overflow.\n     *\n     * Counterpart to Solidity\'s `+` operator.\n     *\n     * Requirements:\n     * - Addition cannot overflow.\n     */\n    function add(uint256 a, uint256 b) internal pure returns (uint256) {\n        uint256 c = a + b;\n        require(c >= a, "SafeMath: addition overflow");\n\n        return c;\n    }\n\n    /**\n     * @dev Returns the subtraction of two unsigned integers, reverting on\n     * overflow (when the result is negative).\n     *\n     * Counterpart to Solidity\'s `-` operator.\n     *\n     * Requirements:\n     * - Subtraction cannot overflow.\n     */\n    function sub(uint256 a, uint256 b) internal pure returns (uint256) {\n        require(b <= a, "SafeMath: subtraction overflow");\n ........

The contract can be found here if you wanna try: https://github.com/syscoin/sysethereum-contracts. All of the contracts fail to verify.

Notice the '\n' characters.. those are added to the sourceMap and etherscan doesn't seem to like it. Is there a way to strip them out before giving to etherscan? I manually tried a file and confirmed it works but when using the '\n' sourcemap it complains manually aswell.

Thanks for the look!

**Comment by rkalis** [comment] 2019-07-12 02:06
Hmm. When trying it out I get a different sourceCode field for SyscoinBattleManager, but it also doesn't verify correctly.

I tried the following ways:

* Outputted all information from the plugin, and manually copy-pasting it into the Etherscan verification form. This succeeded.
    ![Manual verification](https://i.imgur.com/OiNIDH0.png)
* Using the plugin (which should use the exact same information that was used in the manual verification). This failed.
* Manually copy-pasting the information into [Etherscan's API demo](https://rinkeby.etherscan.io/sourcecode-demo.html). This failed as well.
    ![API demo](https://i.imgur.com/ILBwYe7.png)

From this it seems like the verification for this contract is succeeding with the manual form, but failing when using the API (doesn't matter if it's with truffle-plugin-verify or other API usage). This suggests to me that there might be a difference between the manual verification form and the API, but I can't say this for certain, as I might be missing something or making a mistake in the process.

Is there anyone else able to chime in on this? @mtbitcoin maybe?

**Comment by sidhujag** [comment] 2019-07-12 03:00
the only thing i can think of is that the sourceCode field has "\n" for new lines but you put in the actual code, when I did that I get manual verification to work but solc puts "\n" I switched to v5 solidity and it started to do that.

**Comment by mtbitcoin** [comment] 2019-07-12 12:12
We're looking into this for you and will revert once we have a fix or know what the issue is. Thank you

**Comment by sidhujag** [comment] 2019-07-12 17:31
> We're looking into this for you and will revert once we have a fix or know what the issue is. Thank you

thanks your a star

**Comment by mtbitcoin** [comment] 2019-07-12 17:36
We're still testing the fix but the https://rinkeby.etherscan.io/address/0x47c450c0c189e4e6ddbe84adcb4ff7e3e06d0601#code has been verified

**Comment by sidhujag** [comment] 2019-07-13 16:12
Nice let me know I can redeploy and try it

**Comment by kvrnc** [comment] 2019-07-15 10:32
> Nice let me know I can redeploy and try it

A fix has been updated, kindly give it another try.

Kav

**Comment by sidhujag** [comment] 2019-07-17 23:25
> > Nice let me know I can redeploy and try it
> 
> A fix has been updated, kindly give it another try.
> 
> Kav

Hi Kav,

Where is the fix? What do I pull?

**Comment by rkalis** [comment] 2019-07-18 04:19
Awesome! I just tried it out as well, seems to be working well. Thanks for the fix @mtbitcoin @kvrnc. Closing this issue.

**Closed by rkalis** 2019-07-18 04:19 UTC
